### ISSUE TITLE
Dell Latitude 5480 - Installation Big Sur 11.4

### ISSUE THREAD

**Issue by Papaiamen** [anunna/Dell_Latitude_5480_EFI_OC#1]
did anybody succeed installating last version of Big Sur on an Dell Latitude 5480 and solved issue for mouse and keyboard?
Mine has:
Skylake i5-6440HQ CPU @2.60GHz
Chipset skylake-H
Intel HD 530 graphics
 
I created my pendrive 64gb usb type-c with Big Sur OS 
With Opencore used EFI folder from Anunna's user (really thanks)

**Comment by anunna** [comment]
I am planning to do a fresh setup of OC on a Dell Latitude 5480 on the latest version of OC and MacOS because I only kept upgrading my plist from before Big Sur was out and adapted it . The OC I have here is 0.5.6 and I could never get the keyboard and trackpad to work on Big Sur, but I could get the keyboard to work on Catalina. 

I will give this a fresh attempt and let you know if I can get it working on the latest of everything.

**Comment by Papaiamen** [comment]
Thank you very much for your reply, I am in your hands to be able to install Big Sur on this notebook
Can you post the link of the iso of the operating system that is working in yours, together with the other tools, perhaps with a tutorial that can help me in the installation? At least to test and try if I'm fine, waiting for your final version.

**Comment by Papaiamen** [comment]
Ciao Anunna how are you? :)
do you have an update regarding this?
I still not able to install it in my laptop :(

**Comment by anunna** [comment]
I am good thanks. I am currently working on getting the latest MacOS Monterey (12) working with a fresh OC and new drivers, etc.

**Comment by anunna** [comment]
@Papaiamen I have finally fixed the keyboard and touchpad working on Monterey 12.3.1. All keyboard functions and touchpad gestures are working too. 

[ff1f2ff](https://github.com/anunna/Dell_Latitude_5480_EFI_OC/commit/ff1f2ff11207b597077bb1be2fea767894ca9a89)

**Comment by Papaiamen** [comment]
Ciao :)
Really thank you for this information you made my day!

Do you have a tutorial I can follow step by step  for install the OS in our
notebook latitude 5480 and makes everything working?


Il ven 22 apr 2022, 22:34 Alia Morozova ***@***.***> ha
scritto:

**Comment by anunna** [comment]
You can just make your flash drive and copy the my EFI on there, and download the latest version of MacOS 12 recovery from this [page](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/linux-install.html#downloading-macos) and put in your `com.apple.recovery.boot` folder.

Then boot the flash and select option 2 if I remember is "macOS Base System (External)" or something like that. Format disk on `GUID partition Scheme` and `APFS` and select reinstall MacOS once you close the disk utility.

This should just work, you'll have keyboard, touchpad, WiFi, Ethernet, etc. from the setup already. 
![Screenshot 2022-04-22 at 22 54 08](https://user-images.githubusercontent.com/56030294/164793083-89ab069e-c2a8-4299-b6d3-0b30497d3883.png)

**Comment by Papaiamen** [comment]
Hi,
I am having a problem with disk C and I dont know the reason
As you can see attached I cannot erase or make any change to my had disk
(named here disk0s3 )
I don't know why says 255gb used and no space available.

Ps: mouse etc is working ;)


Il ven 22 apr 2022, 23:00 Alia Morozova ***@***.***> ha
scritto:

**Comment by Papaiamen** [comment]
I made video for show u better the issue.

https://www.veed.io/view/64739ad4-7dbf-490d-a69d-3a4acb759847?sharingWidget=true

**Comment by Papaiamen** [comment]
Hey i solved everything i can say
for avoid this issue i just changed the OS monterey with the big sur, and i
did not have the problem with hard disk.

after that i updated big sure in monterey and everything works.

the only question i have.
there is a way to remove the usb pendrive and booting the os just with the
notebook?
how can i do that?

really thank you



•  Alessio Noli

•  IT & Automotive Specialist

   Entrepreneur ✍


***@***.*** ***@***.***>*

*• * *+48662706254*

•  90-644 Lodz - Poland



Il giorno sab 23 apr 2022 alle ore 11:43 Alessio Noli ***@***.***>
ha scritto:

**Comment by anunna** [comment]
I had this same issue with the disk. I didn't have it with an earlier version of Monterey, so I haven't found what Apple changed. The only way I could get passed it was to boot into a live Linux ISO and create a blank GPT disk. When I went back into the MacOS Disk Utility, I could properly format the disk. Your way also works fine but its just the long way lol. 

Regarding moving the. EFI files to the laptop, you can follow the steps [here](https://dortania.github.io/OpenCore-Post-Install/universal/oc2hdd.html#grabbing-opencore-off-the-usb), very quick and straightforward. 

Basically you would run `MountEFI`, enter `B` to mount the EFI partition of the laptop. Delete the `Apple` folder inside the partition (drive should be blank) and then copy only the `EFI` folder from your flash drive to this portion. When you reboot, from OpenCore boot selector, first select `Reset NVRAM` to avoid any issues, it will reboot and then you can boot normally. (Obviously remove the flash drive when you reboot to avoid getting to the wrong boot loader.  

I did notice that my brightness keys do not work on the keyboard, but volume keys etc. works. This is the only issue I have left, I am experimenting with better audio drivers too, and will let you know if you should update to that.

**Comment by Papaiamen** [comment]
Hey
I managed to fix the mountEFI and now i am not using usb pendrive and i
think is a good point .
for what i can see even in my keyboard is not working the brightness.
I realised also that for example when i have to delete a file, usually i
was pressing Delete button from the keyboard but doesnt work. i have to do
right click and then select move to the bin
As you said yes the audio part is not the best one, and i would like to
improve it.
I do not see any other bug, looks working fine for the rest. Thanks to you
Keep me updated for improvements





•  Alessio Noli

•  IT & Automotive Specialist

   Entrepreneur ✍


***@***.*** ***@***.***>*

*• * *+48662706254*

•  90-644 Lodz - Poland



Il giorno sab 23 apr 2022 alle ore 21:26 Alia Morozova <
***@***.***> ha scritto:

**Comment by Papaiamen** [comment]
ps: i realised also that all my pendrives usb , i have two both of them are
not recognised now from my notebook
but is i plug them in my other notebook with Windows 10, they works fine.

How i can fix this? I do not want to lose my files.



•  Alessio Noli

•  IT & Automotive Specialist

   Entrepreneur ✍


***@***.*** ***@***.***>*

*• * *+48662706254*

•  90-644 Lodz - Poland



Il giorno lun 25 apr 2022 alle ore 10:55 Alessio Noli ***@***.***>
ha scritto:

**Comment by Papaiamen** [comment]
PS: Even the mmc reader is not working , i have a microsd but she is not
recognised as well



•  Alessio Noli

•  IT & Automotive Specialist

   Entrepreneur ✍


***@***.*** ***@***.***>*

*• * *+48662706254*

•  90-644 Lodz - Poland



Il giorno lun 25 apr 2022 alle ore 11:19 Alessio Noli ***@***.***>
ha scritto:
